version: "3.8"
services:
  app:
    image: 10.254.55.75/tenex_container_simple
    build: .
    env_file:
      - .env
    volumes:
      - tenex_container_simple:/app
    command: [ "random_env.yml" ]
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 8g
        reservations:
          cpus: "1.0"
          memory: 2g

volumes:
  tenex_container_simple: